steps:
  dev:
    image: python:3.12-slim
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.dev
    commands:
      - pip install -r requirements.txt
      - python manage.py migrate
      - python manage.py loaddata dev_fixtures.json
      - python manage.py test

  test:
    image: python:3.12-slim
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.test
    commands:
      - pip install -r requirements.txt
      - python manage.py migrate
      - python manage.py test

  deploy:
    image: docker:latest
    secrets: [ docker_user, docker_pass ]
    commands:
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - docker build -t myapp:${CI_COMMIT_SHA} .
      - docker push myapp:${CI_COMMIT_SHA}

